DEBUG 2018-10-19 11:34:10,370: 	 Executing command: 'submit'
DEBUG 2018-10-19 11:34:10,373: 	 Found CRAB cache file /afs/cern.ch/user/g/gbakas/.crab3
DEBUG 2018-10-19 11:34:10,389: 	 Checking credentials
DEBUG 2018-10-19 11:34:10,390: 	 Found proxy file /tmp/x509up_u107749
DEBUG 2018-10-19 11:34:10,390: 	 Getting proxy life time left
DEBUG 2018-10-19 11:34:11,098: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107749 -timeleft
 output : 604310

 error: 
 retcode : 0
DEBUG 2018-10-19 11:34:11,804: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107749 -actimeleft
 output : 604310

 error: 
 retcode : 0
DEBUG 2018-10-19 11:34:11,805: 	 Proxy valid for 167:51:50 hours
ERROR 2018-10-19 11:34:11,805: 	 CRAB configuration file CreateCrabConfigFilesData.py not found.
ERROR 2018-10-19 11:34:11,805: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 303, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1809-comp/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 46, in loadConfig
    raise ConfigurationException("CRAB configuration file %s not found." % (configname))
ConfigurationException: CRAB configuration file CreateCrabConfigFilesData.py not found.
